// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {flathub} from '../models';

export function GetAppsByCategory(arg1:string):Promise<Array<flathub.AppSummary>>;

export function GetDiscoverApps():Promise<Array<flathub.AppSummary>>;

export function GetInstalledApps():Promise<Array<flathub.InstalledApp>>;

export function InstallApp(arg1:string,arg2:boolean):Promise<void>;

export function SearchApps(arg1:string):Promise<Array<flathub.AppSummary>>;

export function UninstallApp(arg1:string,arg2:boolean):Promise<void>;

export function UpdateApp(arg1:string,arg2:boolean):Promise<void>;
