// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppsByCategory(arg1) {
  return window['go']['main']['App']['GetAppsByCategory'](arg1);
}

export function GetDiscoverApps() {
  return window['go']['main']['App']['GetDiscoverApps']();
}

export function InstallApp(arg1, arg2) {
  return window['go']['main']['App']['InstallApp'](arg1, arg2);
}

export function SearchApps(arg1) {
  return window['go']['main']['App']['SearchApps'](arg1);
}
