// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppDetails(arg1) {
  return window['go']['main']['App']['GetAppDetails'](arg1);
}

export function GetAppsByCategory(arg1) {
  return window['go']['main']['App']['GetAppsByCategory'](arg1);
}

export function GetAppsByDeveloper(arg1) {
  return window['go']['main']['App']['GetAppsByDeveloper'](arg1);
}

export function GetDiscoverApps() {
  return window['go']['main']['App']['GetDiscoverApps']();
}

export function GetInstalledApps() {
  return window['go']['main']['App']['GetInstalledApps']();
}

export function GetPopularApps() {
  return window['go']['main']['App']['GetPopularApps']();
}

export function GetPopularCreate() {
  return window['go']['main']['App']['GetPopularCreate']();
}

export function GetPopularGames() {
  return window['go']['main']['App']['GetPopularGames']();
}

export function InstallApp(arg1, arg2) {
  return window['go']['main']['App']['InstallApp'](arg1, arg2);
}

export function IsCatalogReady() {
  return window['go']['main']['App']['IsCatalogReady']();
}

export function OpenApp(arg1) {
  return window['go']['main']['App']['OpenApp'](arg1);
}

export function SearchApps(arg1) {
  return window['go']['main']['App']['SearchApps'](arg1);
}

export function UninstallApp(arg1, arg2) {
  return window['go']['main']['App']['UninstallApp'](arg1, arg2);
}

export function UpdateApp(arg1, arg2) {
  return window['go']['main']['App']['UpdateApp'](arg1, arg2);
}
